version: "3.8"

services:
  # Backend - Python FastAPI Game Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://tannenbaum:password@postgres:5432/tannenbaumbiel_dev

      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend - Node.js Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tannenbaumbiel_dev
      - POSTGRES_USER=tannenbaum
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deployment/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tannenbaum -d tannenbaumbiel_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx Reverse Proxy (Optional for production-like setup)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #   restart: unless-stopped

  # Selenium Test Service (run manually with: docker compose run --rm test)
  test:
    image: python:3.11-slim
    working_dir: /app/tools
    volumes:
      - ./tools:/app/tools
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY:-:0}
    depends_on:
      - frontend
      - backend
      - postgres
    profiles:
      - test
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y wget gnupg2 curl unzip &&
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - &&
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list &&
        apt-get update &&
        apt-get install -y google-chrome-stable &&
        pip install -r test_requirements.txt &&
        python selenium_test.py
      "

volumes:
  postgres_data:

networks:
  default:
    name: tannenbaumbiel-network
